---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

12.1 Prerequisites
- Create a GitHub account (completed)
- Installed/updated R and RStudio (completed)
- You've installed Git (completed)
- You've introduced yourself to Git (completed)
- You've confirmed that you can push / pull from GitHub with command line (completed)

12.2 Make a Repo in GitHub
Completed this task with no error by using the links provided in the DS 2020 html.

12.3 Clone the test GitHub repository to your computer via RStudio
Completed with no errors.

12.4 Make local changes, save, commit
Updates not reflected in GitHub server side, this error was due to failure to git push the update. 

12.5 Push your local changes online to GitHub
Completed without error.

12.6 Confirm the local change propagated to the GitHub remote
The proper edits were reflected in the remote README.md file.

12.7 Clean up
N/A
